baseurl = "http://mateusz.matoszko.pl/"
languageCode = "en-us"
title = "Mateusz Matoszko"
newContentEditor = "vim"
theme = "hugo-steam-theme"
# disqusShortname = "mmatoszko"
pygmentsStyle = "native"
paginate = 10

[params]

	title = "Mateusz Matoszko"
	subtitle = "Mobile Engineer"
	copyright = ""

	# You can choose between green, orange, red and blue.
	themeColor = "blue"
	# Enable Google Analytics be inserting your tracking code
	googleAnalytics = "UA-76600443-1"

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "Mateusz Matoszko"
    bio = ""
	description = "I like to make mobile apps that people enjoy using. Blogging about technical details at nshint.io."
	location = "Poland" # optional
	twitter = "mmatoszko" # optional
	github = "mmatoszko" # optional

	# Enable a comment system
	# You can choose between Disqus or Google Plus by setting comments
	# to disqus or googleplus. For using Disqus you need to enter your
	# shortname in disqusShortname at the top of the configs. 
	# comments = "disqus"

	# Customize or translate the strings
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"
